# Generated by Django 5.0.7 on 2024-09-16 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerhaApp', '0003_user_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollNo', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=128)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
