# Generated by Django 5.0.7 on 2024-09-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerhaApp', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isStudent',
            field=models.BooleanField(default=True),
        ),
    ]
