# Generated by Django 5.0.7 on 2024-09-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerhaApp', '0005_user_isstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isDriver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
    ]
