# Generated by Django 5.0.7 on 2024-09-18 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerhaApp', '0006_user_isdriver_alter_user_isstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('vehicleNo', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
