# Generated by Django 5.0.7 on 2024-10-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerhaApp', '0010_driver_location_alter_driver_phn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
