# Generated by Django 5.0.7 on 2024-10-07 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerhaApp', '0011_alter_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='cerhaApp.student'),
        ),
    ]
