# Generated by Django 5.0.7 on 2024-10-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerhaApp', '0014_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time_taken',
            field=models.FloatField(default=0.0),
        ),
    ]
