# Generated by Django 5.0.7 on 2024-10-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerhaApp', '0015_request_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicleNo',
            field=models.IntegerField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNo',
            field=models.IntegerField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
