# Generated by Django 5.0.7 on 2024-10-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerhaApp', '0018_student_id_alter_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicleNo',
            field=models.IntegerField(max_length=9, unique=True),
        ),
    ]
