# Generated by Django 5.0.7 on 2024-10-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerhaApp', '0019_driver_id_alter_driver_vehicleno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicleNo',
            field=models.IntegerField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNo',
            field=models.IntegerField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
