# Generated by Django 5.0.7 on 2024-11-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerhaApp', '0020_remove_driver_id_remove_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='student@gmail.com', max_length=254),
        ),
    ]
